#Lors d'un commit contenant la clé [deploy] on envoi vers le FTP du build
name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    #if: contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.4.0
        with:
          server: ftp://ftp.swco2529.odns.fr
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build
          server-dir: /
